baseurl = "http://blog.milkpod29.me/"
languageCode = "en-us"
canonifyurls = true
contentdir = "content"
publishdir = "public"
builddrafts = false
theme = "cheddar"
MetaDataFormat = "toml"
title = "Persistence pays off."
author = "Yuichi Saito"

[indexes]
    category = "categories"
    tag = "tags"
