baseurl = "http://blog.milkpod29.me/"
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
title = "My New Hugo Site"
author = "Yuichi Saito"

[indexes]
    category = "categories"
    tag = "tags"
